### PR TITLE
add option to specify baudrate

### PR DESCRIPTION
**Pull request by semininja**
added argument to `__init__` to allow users to set baudrate if desired

retains previous default if unspecified

### CODE REVIEW

**Comment by semininja** [comment]
I don't know enough about how the CI checks work to be able to tell why `black` is somehow causing this to fail; it doesn't appear that the actual function was tested.

**Review by tekktrik — APPROVED** [review]
Good addition, thanks for the PR!

**Review by tekktrik — CHANGES_REQUESTED** [review]
Sorry, I meant to respond to your followup about `black`.  If you run `pre-commit`, it should reformat things accordingly so it will pass if you submit the changes it makes.  You can find information on using `pre-commit` here:

https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code

**Comment by semininja** [comment]
Unfortunately, I'm not able to run `pre-commit` successfully for some reason. Here's what appears to be the relevant chunk from the log:

          _ruamel_yaml.c:6:10: fatal error: Python.h: No such file or directory
              6 | #include "Python.h"
                |          ^~~~~~~~~~
          compilation terminated.
          error: command '/usr/bin/gcc' failed with exit code 1
          [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: legacy-install-failure

    × Encountered error while trying to install package.
    ╰─> ruamel.yaml.clib

**Review by tekktrik — APPROVED** [review]
Looks like it was an extra bit of whitespace causing the issue.  Thanks!

**Pull request merged**
