### PR TITLE
Updated build.yml and release.yml

### PR DESCRIPTION
**Pull request by evaherrada**

### CODE REVIEW

**Review by makermelissa — CHANGES_REQUESTED** [review]
Can we add `pip install -r requirements.txt` back in? 
Thanks.

**Review by siddacious — APPROVED** [review]

**Comment by evaherrada** [comment]
@makermelissa Sure. @siddacious, I should make another pr to the test repo, right?

**Comment by siddacious** [comment]
@makermelissa `pip install -r requirements.txt` is defined in the `install.sh` but since the script is invoked as `actions-ci/install.sh` it will use the repo-local requirements.txt, right?

**Comment by siddacious** [comment]
By which I mean it hasn't been removed, just moved.

**Comment by makermelissa** [comment]
Actually, I'm not sure. If it's reading requirements.txt out of the other repo, than it needs to be added here and if it's reading out of this repo, it's fine. Can we test that?

**Comment by makermelissa** [comment]
Ok, you're right. This is all good.

**Review by makermelissa — APPROVED** [review]

**Pull request merged**
