### PR TITLE
Travis to github actions

### PR DESCRIPTION
**Pull request by evaherrada**

### CODE REVIEW

**Review by siddacious — CHANGES_REQUESTED** [review]
Looks good, though please also remove the `.travis.yml`

**Comment by evaherrada** [comment]
@siddacious done

**Review by siddacious — CHANGES_REQUESTED** [review]
Looks like the build.yml wasn't added because the .gitignore was updated after it was added. Go ahead and add it again

**Comment by evaherrada** [comment]
@siddacious Ok, I've pushed that file. That's good to know so I can make sure to do it in that order when I automate it

**Review by siddacious — APPROVED** [review]

**Comment by siddacious** [comment]
@dherrada looks good; I'll merge, then make a PR against this library with some change with a pylint error and we'll see if it works!

**Comment by evaherrada** [comment]
@siddacious Ok

**Pull request merged**
